<?php

use Illuminate\Database\Seeder;

class carTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('car')->insert([
        [
           'brand' => 'Hyundai',
           'model' => 'I20',
           'color' => 'Black',
           'description' => 'this car is hyundai I20',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
       	],
        [
           'brand' => 'Hyundai',
           'model' => '3D MAXpider',
           'color' => 'Orange',
           'description' => 'this car is hyndai 3D MAXpider',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Venue',
           'color' => 'Blue Metallic',
           'description' => 'this car hyundai venue',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Creta',
           'color' => 'Mariana Blue',
           'description' => 'this car Hyundai Creta',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Grand i10',
           'color' => 'Polar White',
           'description' => 'this car Hyundai Grand i10',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Verna',
           'color' => 'Black',
           'description' => 'this car Hyundai Verna',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Santro',
           'color' => 'Silver',
           'description' => 'this car Hyundai Santro',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Xcent',
           'color' => 'Dust',
           'description' => 'this car Hyundai Xcent',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'i20 Active',
           'color' => 'Earth Brown',
           'description' => 'this car Hyundai i20 Active',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Elantra',
           'color' => 'Phantom Black',
           'description' => 'this car Hyundai Elantra',
           'fuel_type' => 'petrol',
           'image' => '1560314567.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Creta',
           'color' => 'White',
           'description' => 'this car',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
       	],
        [
           'brand' => 'Hyundai',
           'model' => 'Tucson',
           'color' => 'Polar White',
           'description' => 'this car Hyundai Tucson',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Kona Electric',
           'color' => 'Marine Blue',
           'description' => 'this car Hyundai Kona Electric',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Sonata',
           'color' => 'Mushroom',
           'description' => 'this car Hyundai Sonata',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Santa Fe 2019',
           'color' => 'Blue',
           'description' => 'this car Hyundai Santa Fe 2019',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Palisade',
           'color' => 'Black',
           'description' => 'this car Hyundai Palisade',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Ioniq',
           'color' => 'Silver',
           'description' => 'this car Hyundai Ioniq',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Hyundai',
           'model' => 'Creta',
           'color' => 'White',
           'description' => 'this car',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => 'X1',
           'color' => 'Estoril Blue',
           'description' => 'this car BMW X1',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => 'Z4',
           'color' => 'Greny',
           'description' => 'this car BMW Z4',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => '3 Series GT',
           'color' => 'Jatoba',
           'description' => 'this car BMW 3 Series GT',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => '7 Series',
           'color' => 'Mineral White',
           'description' => 'this car BMW 7 Series',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => 'X5',
           'color' => 'Blue',
           'description' => 'this car BMW X5',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => 'X4',
           'color' => 'Red',
           'description' => 'this car BMW X4',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => 'X6',
           'color' => 'Blue',
           'description' => 'this car BMW X6',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => '3 Series',
           'color' => 'Estoril Blue',
           'description' => 'this car BMW 3 Series',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'BMW',
           'model' => '6 Series',
           'color' => 'Red',
           'description' => 'this car BMW 6 Series',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'EcoSport',
           'color' => 'Race Red',
           'description' => 'this car Ford EcoSport',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'Endeavour',
           'color' => 'Absolute Black',
           'description' => 'this car Ford Endeavour',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'Mustang',
           'color' => 'Tripal Yellow',
           'description' => 'this car Ford Mustang',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'Figo',
           'color' => 'Deep Blue',
           'description' => 'this car Ford Figo',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'Aspire',
           'color' => 'Smoke Grey',
           'description' => 'this car Ford Aspire',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Ford',
           'model' => 'Freestyle',
           'color' => 'Moondust Silver',
           'description' => 'this car Ford Freestyle',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Lamborghini',
           'model' => 'Huracan',
           'color' => 'Green',
           'description' => 'this car Lamborghini Huracan',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Lamborghini',
           'model' => 'Urus',
           'color' => 'Blue',
           'description' => 'this car Lamborghini Urus',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Lamborghini',
           'model' => 'Huracan EVO',
           'color' => 'Sunsat Orange',
           'description' => 'this car Lamborghini Huracan EVO',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Mahindra',
           'model' => 'XUV300',
           'color' => 'Dual-tone Red',
           'description' => 'this car Mahindra XUV300',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Mahindra',
           'model' => 'Scorpio',
           'color' => 'White',
           'description' => 'this car Mahindra Scorpio',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Mahindra',
           'model' => 'XUV500',
           'color' => 'Red',
           'description' => 'this car Mahindra XUV500',
           'fuel_type' => 'diesel',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Mahindra',
           'model' => 'Thar',
           'color' => 'Blue',
           'description' => 'this car Mahindra Thar',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'KWID',
           'color' => 'Moonlight Silver',
           'description' => 'this car Renault KWID',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Duster',
           'color' => 'Blue',
           'description' => 'this car Renault Duster',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Lodgy',
           'color' => 'Red',
           'description' => 'this car Renault Lodgy',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Captur',
           'color' => 'Orange',
           'description' => 'this car Renault Captur',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Triber',
           'color' => 'Yellow',
           'description' => 'this car Renault Triber',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'KWID',
           'color' => 'Moonlight Silver',
           'description' => 'this car Renault KWID',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'HBC',
           'color' => 'Yellow',
           'description' => 'this car Renault HBC',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'KWID 2019',
           'color' => 'White',
           'description' => 'this car Renault KWID 2019',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Zoe',
           'color' => 'Blue',
           'description' => 'this car Renault Zoe',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Renault',
           'model' => 'Kwid EV',
           'color' => 'White',
           'description' => 'this car Renault Kwid EV',
           'fuel_type' => 'petrol',
           'image' => '1560314773.png',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ]
       ]);
    }
}
