<?php

use Illuminate\Database\Seeder;

class mobileTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mobile')->insert([
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'S7',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
       	],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'M40',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'M20',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'M30',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'A50',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'A70',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'A30',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'A10',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'A20',
           'color' => 'White',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Samsung Galaxy',
           'model' => 'M20',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => 'X',
           'color' => 'White',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
       	],
        [
           'brand' => 'Apple iPhone',
           'model' => 'XR',
           'color' => 'Silver',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => '11',
           'color' => 'Black',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => '7 Plus',
           'color' => 'Black',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => '7',
           'color' => 'Silver',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => 'XS Max',
           'color' => 'Black',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => 'XS',
           'color' => 'White',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => '6s',
           'color' => 'White',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => '8',
           'color' => 'Black',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Apple iPhone',
           'model' => 'SE',
           'color' => 'White',
           'description' => 'This mobile feature very smart',
           'os_type' => 'IOS',
           'image' => '1562758941.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Note 7 Pro',
           'color' => 'Dark Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => '7',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Y3',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Note 7S',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Note 7',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Note 7 Pro 128GB',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi',
           'model' => 'Mi A2 (Mi 6X)',
           'color' => 'Silver',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => '6A',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => '6',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Xiaomi Redmi',
           'model' => 'Note 6 Pro',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Z1 Pro',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'V15 Pro',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'V15',
           'color' => 'White',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y15 2019',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y17',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y91',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'V9',
           'color' => 'Black',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y12',
           'color' => 'Red',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y91i',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
           'brand' => 'Vivo',
           'model' => 'Y95',
           'color' => 'Blue',
           'description' => 'This mobile is very smart',
           'os_type' => 'android',
           'image' => '1562758880.jpg',
           'created_at' => date('Y-m-d H:i:s'),
           'updated_at' => date('Y-m-d H:i:s'),
        ]
      ]);
    }
}
